version: '3.7'

services:
  shadowsocks:
    image: ghcr.io/shadowsocks/sslocal-rust:latest
    volumes:
      - './config.json:/etc/shadowsocks-rust/config.json'
  example:
    build: .
    ports:
      - '127.0.0.1:9090:9090'
  